/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.1+p38-gf512b381
 *
 * Project: 'calibrator.release+DevKit-E8-HP' 
 * Target:  'release+DevKit-E8-HP' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* AlifSemiconductor::CMSIS Driver:USART@2.2.0 */
#define RTE_Drivers_USART               /* Driver UART  */
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@2.2.0 */
#define RTE_Drivers_IO              /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:OSPI@2.2.0 */
#define RTE_Drivers_OSPI              /* Driver OSPI */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@2.2.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */


#endif /* RTE_COMPONENTS_H */
